"""change field names to english

Revision ID: 0abd33d80a60
Revises: 437d20caee4d
Create Date: 2023-12-16 15:06:24.887279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abd33d80a60'
down_revision = '437d20caee4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))
        batch_op.drop_column('wydawnictwo')
        batch_op.drop_column('rok_wydania')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rok_wydania', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wydawnictwo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('publisher')
        batch_op.drop_column('publication_year')

    # ### end Alembic commands ###
