"""Dodanie pola pesel oraz image do modeli

Revision ID: 10dc0ef75c89
Revises: 869ec5bdf8b0
Create Date: 2023-12-10 21:51:16.162294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dc0ef75c89'
down_revision = '869ec5bdf8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesel', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint(None, ['pesel'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pesel')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
