"""Added pesel, address, postal_code, and city to borrowers

Revision ID: 469f3734653a
Revises: 0abd33d80a60
Create Date: 2023-12-18 22:02:45.028730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469f3734653a'
down_revision = '0abd33d80a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesel', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['pesel'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address')
        batch_op.drop_column('pesel')

    # ### end Alembic commands ###
