"""Update book author relationship

Revision ID: 6080132c4f87
Revises: 9fa5e3e2b07a
Create Date: 2023-12-15 19:23:44.567307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6080132c4f87'
down_revision = '9fa5e3e2b07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_author_id_fkey', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('books_author_id_fkey', 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###
