"""Dodanie tabeli autora

Revision ID: 869ec5bdf8b0
Revises: 4e8e64da5ac3
Create Date: 2023-11-30 00:05:27.387116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869ec5bdf8b0'
down_revision = '4e8e64da5ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_books_author')
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_books_author', ['author'], unique=False)
        batch_op.drop_column('author_id')

    op.drop_table('authors')
    # ### end Alembic commands ###
