"""add quantity to bokks

Revision ID: 9fa5e3e2b07a
Revises: da9c5dfa28d7
Create Date: 2023-12-15 18:32:32.439122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa5e3e2b07a'
down_revision = 'da9c5dfa28d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
