"""minor changes in the schema of the database.

Revision ID: efb1e78d1318
Revises: 469f3734653a
Create Date: 2023-12-28 16:49:19.224618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efb1e78d1318'
down_revision = '469f3734653a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('reservations')
    op.drop_table('reports')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('loans_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('loans_employee_id_fkey', 'employees', ['employee_id'], ['id'])

    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name='reports_generated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reservation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='reservations_book_id_fkey'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name='reservations_borrower_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservations_pkey')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    # ### end Alembic commands ###
